# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm install
    - run: npm run build
    
    - name: Zip Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'slbingoui-win32-x64.zip'
        path: 'slbingoui-win32-x64'
        
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE
          slbingoui-win32-x64.zip
